// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package manager

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID         int32
	Title      string
	Author     string
	Year       pgtype.Int4
	IsBorrowed pgtype.Bool
}

type Borrow struct {
	ID         int32
	UserID     pgtype.Int4
	BookID     pgtype.Int4
	BorrowedAt pgtype.Timestamp
	ReturnedAt pgtype.Timestamp
}

type User struct {
	ID    int32
	Name  string
	Email string
}
